### ISSUE TITLE
sd-webui-traintrainの拡張機能が読み込まれない

### ISSUE THREAD

**Issue by waomodder** [hako-mikan/sd-webui-traintrain#11]
こんにちは。この拡張機能をインストールして使おうとしたら、まったくUIにタブが表示されませんでした。
バージョンはv1.7.0です。

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing requirements
Installing diffusers==0.20.0
Installing invisible-watermark==0.2.0

```
*** Error loading script: traintrain.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-traintrain\scripts\traintrain.py", line 12, in <module>
        from trainer import train, trainer, gen
      File "D:\stable-diffusion-webui\extensions\sd-webui-traintrain\trainer\train.py", line 13, in <module>
        from trainer.lora import LoRANetwork, LycorisNetwork
      File "D:\stable-diffusion-webui\extensions\sd-webui-traintrain\trainer\lora.py", line 365, in <module>
        from lycoris.modules.loha import LohaModule
      File "D:\stable-diffusion-webui\venv\lib\site-packages\lycoris\__init__.py", line 1, in <module>
        from . import (
      File "D:\stable-diffusion-webui\venv\lib\site-packages\lycoris\kohya\__init__.py", line 18, in <module>
        from ..wrapper import LycorisNetwork
      File "D:\stable-diffusion-webui\venv\lib\site-packages\lycoris\wrapper.py", line 21, in <module>
        from .modules.diag_oft import DiagOFTModule
      File "D:\stable-diffusion-webui\venv\lib\site-packages\lycoris\modules\diag_oft.py", line 144
        weight = self.rescale[:, *(None for _ in weight.shape[1:])] * weight
                                 ^
    SyntaxError: invalid syntax
```

**Comment by waomodder** [comment]
自己解決しました。この拡張の設定の「Disable taking the average value when calculating cond/uncond」チェックを外したら動きました。
https://github.com/hako-mikan/sd-webui-prevent-artifact
