### ISSUE TITLE
Error: cannot pin 'torch.cuda.FloatTensor'

### ISSUE THREAD

**Issue by JeltzProstetnic** [hako-mikan/sd-webui-traintrain#20]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.4
CUDA 12.1

Create LoRA for Textencoder : 264 modules.
  0%|                                                                                         | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\_AI\sd.webui.deforum\webui\extensions\sd-webui-traintrain\trainer\train.py", line 195, in train_main
    result = train_lora(t)
  File "C:\_AI\sd.webui.deforum\webui\extensions\sd-webui-traintrain\trainer\train.py", line 248, in train_lora
    for batch in t.dataloader:
  File "C:\_AI\sd.webui.deforum\webui\extensions\sd-webui-traintrain\trainer\dataset.py", line 52, in __next__
    return next(self.iterators[idx])
  File "C:\_AI\sd.webui.deforum\system\python\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\_AI\sd.webui.deforum\system\python\lib\site-packages\torch\utils\data\dataloader.py", line 676, in _next_data
    data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)
  File "C:\_AI\sd.webui.deforum\system\python\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 63, in pin_memory
    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
  File "C:\_AI\sd.webui.deforum\system\python\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 63, in <dictcomp>
    return type(data)({k: pin_memory(sample, device) for k, sample in data.items()})  # type: ignore[call-arg]
  File "C:\_AI\sd.webui.deforum\system\python\lib\site-packages\torch\utils\data\_utils\pin_memory.py", line 58, in pin_memory
    return data.pin_memory(device)
RuntimeError: cannot pin 'torch.cuda.FloatTensor' only dense CPU tensors can be pinned

**Comment by hako-mikan** [comment]
Fixed.
