### ISSUE TITLE
BlockFunction' object has no attribute 'input'

### ISSUE THREAD

**Issue by zentrocdot** [hako-mikan/sd-webui-traintrain#23]
I get for about an hour following error message while starting the local server:

*** Error executing callback app_started_callback for /home/hades/ssd-sandisk/stable-diffusion-webui/extensions/sd-webui-traintrain/scripts/traintrain.py
    Traceback (most recent call last):
      File "/home/hades/ssd-sandisk/stable-diffusion-webui/modules/script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "/home/hades/ssd-sandisk/stable-diffusion-webui/extensions/sd-webui-traintrain/scripts/traintrain.py", line 632, in get_params_components
        img2img_params = params[0].input
    AttributeError: 'BlockFunction' object has no attribute 'input'

It has to be checked, if error correction can be done by following step:

go into traintrain.py in the extension dir and change line 632 from

` img2img_params = params[0].input`

to

` img2img_params = params[0].inputs`

Doing this the error is gone. The missing 's' makes also sense, due to gradios 'inputs' component . 
                   
Apart from that, I haven't gone into any more detail as I don't need the module next time.

**Comment by hako-mikan** [comment]
Thanks! Fixed.
