### ISSUE TITLE
AttributeError: module 'os' has no attribute 'startfile'

### ISSUE THREAD

**Issue by wangier** [hako-mikan/sd-webui-traintrain#25]
on Ubuntu, while the open folder button was clicked, it did nothing, and an error was printed in the terminal, as below shown. Seems the scripts does not consider platform difference for this feature.

`Traceback (most recent call last):
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/u01/stable-diffusion-webui/extensions/sd-webui-traintrain/scripts/traintrain.py", line 392, in openfolder_f
    os.startfile(jsonspath)
AttributeError: module 'os' has no attribute 'startfile'
`

**Comment by hako-mikan** [comment]
Fixed.

**Comment by wangier** [comment]
Thaks for your work. @hako-mikan 
After pull the latest commit, no error is printed while open folder button clicked, under Ubuntu.
However, it just opens a files explorer. No select button in the poped-up files explorer. Hence the target file could not be selected.
If I input the target file path into inputbox directly, and click the "apply" button, there are many error boxes poped up on every inputbox. In the terminal, the below information was printed out:

Traceback (most recent call last):
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (import_json) didn't receive enough output values (needed: 101, received: 48).
Wanted outputs:
    [radio, dropdown, dropdown, dropdown, dropdown, dropdown, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, textbox, dropdown, textbox, textbox, checkbox, checkboxgroup, dropdown, dropdown, dropdown, dropdown, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, dropdown, dropdown, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, dropdown, dropdown, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, textbox, dropdown, textbox, textbox, checkbox, checkboxgroup, dropdown, dropdown, dropdown, dropdown, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, dropdown, dropdown, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox]
Received outputs:
    [{'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}]

![image](https://github.com/user-attachments/assets/28e26613-ab5e-4778-a0de-ac038f42a9e2)

**Comment by hako-mikan** [comment]
That button is not for selecting files but for opening folders, so it's working as intended. 
Selecting files isn’t possible due to Gradio’s limitations.
Please only input the file name in that text box; it doesn’t matter whether “.json” is included or not.

**Comment by wangier** [comment]
> That button is not for selecting files but for opening folders, so it's working as intended. Selecting files isn’t possible due to Gradio’s limitations. Please only input the file name in that text box; it doesn’t matter whether “.json” is included or not.

Thanks for your reply.

What can I do for the "apply" issue? After target file path inputed into the text box, when I clicked the "apply" button,  many error boxes poped up on every inputbox. In the terminal, the below information was printed out:

Traceback (most recent call last):
File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
output = await app.get_blocks().process_api(
File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
data = self.postprocess_data(fn_index, result["prediction"], state)
File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1297, in postprocess_data
self.validate_outputs(fn_index, predictions) # type: ignore
File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1272, in validate_outputs
raise ValueError(
ValueError: An event handler (import_json) didn't receive enough output values (needed: 101, received: 48).
Wanted outputs:
[radio, dropdown, dropdown, dropdown, dropdown, dropdown, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, textbox, dropdown, textbox, textbox, checkbox, checkboxgroup, dropdown, dropdown, dropdown, dropdown, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, dropdown, dropdown, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, dropdown, dropdown, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, textbox, dropdown, textbox, textbox, checkbox, checkboxgroup, dropdown, dropdown, dropdown, dropdown, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, dropdown, dropdown, dropdown, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox]
Received outputs:
[{'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}, {'type': 'generic_update'}]

[https://private-user-images.githubusercontent.com/3926679/401789874-28e26613-ab5e-4778-a0de-ac038f42a9e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MTk2NDIsIm5iZiI6MTczNjgxOTM0MiwicGF0aCI6Ii8zOTI2Njc5LzQwMTc4OTg3NC0yOGUyNjYxMy1hYjVlLTQ3NzgtYTBkZS1hYzAzOGY0MmE5ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDE0OTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YxNjQwMzVhODM4N2E1NmViODU0NTg2NTUwZmRjNWVjODI3NjIxNzJmZTQ0OTlkZDk2MjhjMjNkZDkzZTlkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uXX_Qk9ywvO13s4xW9pEDfTyqjONXd8tfCzvjJx3Koo](url)

**Comment by hako-mikan** [comment]
Enter only the file name, not the full path.

**Comment by wangier** [comment]
> Enter only the file name, not the full path.

Thanks.
Changed to only file name in putbox, while clicking the apply button, there is somthing new in the logs, as below:  

Traceback (most recent call last):
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/u01/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/u01/stable-diffusion-webui/extensions/sd-webui-traintrain/trainer/trainer.py", line 227, in import_json
    setconfigs(data, output)
  File "/home/u01/stable-diffusion-webui/extensions/sd-webui-traintrain/trainer/trainer.py", line 212, in setconfigs
    from scripts.traintrain import OPTIMIZERS
ModuleNotFoundError: No module named 'scripts.traintrain'

![Image](https://github.com/user-attachments/assets/6b0421a4-e461-4f93-9fd2-52d83a553185)

**Comment by hako-mikan** [comment]
That error often occurs when the extension isn't installed correctly. Try reinstalling it.
Or it might simply be fixed by a restart.
